#!/usr/bin/tclsh

source inc.tcl

set dev1 [DeviceRole TEST     gauge2]
set dev2 [DeviceRole TEST:RTT gauge2]

puts [$dev1 get]
puts [$dev2 get]

$dev1 conf_set maxv 10

puts [$dev2 get]
puts [$dev2 conf_list]

puts [$dev2 conf_get names]
