#!/usr/bin/tclsh

foreach f [glob ../role.tcl ../d_*.tcl ../r_*.tcl] {source $f}

set dev [DeviceRole gen1 burst_source]

$dev set_burst 12000 0.1 100
puts [$dev get_freq]
puts [$dev get_volt]
puts [$dev get_cycl]
